# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20180208_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='session',
        ),
        migrations.AddField(
            model_name='usersession',
            name='evening',
            field=models.CharField(default='No Attendence', max_length=264),
        ),
        migrations.AddField(
            model_name='usersession',
            name='morning',
            field=models.CharField(default='No Attendence', max_length=264),
        ),
    ]
