# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20180208_1135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
