# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 12:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testapp', '0004_delete_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=25)),
                ('t_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
