# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 06:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20170307_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='session',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], default='No Attendence', max_length=25),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='t_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
